version: "3.1"
services:
  app:
    build: .
    image: setlistspy_local_cloud_backend_web
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    entrypoint: ['/usr/src/app/start-local.sh']
    environment:
      API_URL: http://api.setlistspy.com:8000/api/