version: "3.1"
services:
  app:
    build: .
    image: setlistspy_local_web
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    command: ['/usr/src/app/start-local.sh']
    environment:
      API_URL: localhost:6400/api/