version: "3.1"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    command: ['yarn', 'start']
    environment:
      API_URL: localhost:6400/api/