version: "3.1"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    command: ['/usr/src/app/start-production.sh']
    environment:
      API_URL: http://api.setlistspy.com:8000/api/
      PORT: '80'