version: "3.1"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-production
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    command: ['/usr/src/app/start-production.sh']
    environment:
      API_URL: http://api.setlistspy.com:8000/api/
      PORT: '80'